<?php session_start();?>
<?php include('header.php');

?>
<div>
<div class="sh1">
<h1>UNA</h1>
</div>
<div>
<img src="img\178.jpg" height="400px" width="100%">
</div>
		<div>;
		<h2>If tourists are planning to visit Una via roadways, then they should visit a picturesque place called Amb. Amb is a small hill
		station which was once the garden of the renowned king of Jaswal (Chandravanshi Rajput clan). Tourists can also visit the
		famous Bagana Latin Piplu, which is situated on top of Solah Singhi Dhar (hilly range). Bagana Lathian Piplu offers a splendid 
		view of the Govind Sagar Lake, which is located in the vicinity of the place.</h2><br>
		</div>
		<div>
		<img src="img\179.jpg"width="100%">
		</div>
		<div>
		<h2>Una is a district of Himachal Pradesh which lies in its south western part. On
		the 1st September,1972 the Himachal Pradesh Govt. reorganised the then
		Kangra district into three districts namely Una, Hamirpur and Kangra.The 
		famous places of Una are ‘Chintpurni’ Goddess temple, Dera Baba Barbhag 
		Singh, Dera Baba Rudru, Joggi Panga, Dharamshala Mahanta, Dhunsar Mahadev
		Temple Talmehra, Shivbari Temple Gagret and Mini Secretariat. </h2><br>
		</div>
		<div>
		<img src="img\180.jpg"width="100%">
		</div>
  <div class="sh1">
 <h1>TOP EIGHT PLACES</h1>
 </div>
	<div class="sh2">
		<div class="sh5">
		<h3>MATA CHINTPURNI DEVI TEMPLE</h3>
			<img src="img\181.jpg" height="220px" width="300px">
		</div>
		<div class="sh5">
	<h3>RAIPUR MADAN</h3>
			<img src="img\192.jpg" height="220px" width="300px">
		</div>
		<div class="sh5">
		<h3>BANGANA LATHIAN PIPLU</h3> 
			<img src="img\184.jpg" height="220px" width="300px">
		</div>
		<div class="sh5">
		<h3>GOBIND SAGAR LAKE</h3>
		<img src="img\185.jpg" height="220px" width="300px">
		</div>
</div>		
		<div class="y">
		<a href="unaplaces.php"><input type="button" value="See More" name="q" style="padding:15px; color:white; font-size:24px;
	background-color:blue;"></a>
</div>		
